### ISSUE TITLE
静态方法中是不能调用$this的

### ISSUE THREAD

**Issue by xiaoshangmin** [wi1dcard/alipay-sdk-php#10]
AlipayRequestFactory这个工厂类中create是静态方法不能调用$this
```php
 public static function create($classOrApi, $config = [])
    {
        $factory = isset($this) ? $this : new self();  
        if (strpos($classOrApi, '.')) {
            return $factory->createByApi($classOrApi, $config);
        } else {
            return $factory->createByClass($classOrApi, $config);
        }
    }
```

**Comment by wi1dcard** [comment]
PHP 允许静态方法被动态调用，通过 `isset($this)` 可以判断当前方法是否处在类实例的上下文中。因此如果 `isset($this)` 为 TRUE，则可以使用 `$this`，否则创建自身。印象中 Laravel 经常有这种语法糖。

**Comment by xiaoshangmin** [comment]
测试了确实可以 类实例->静态方法 这样调用   涨知识  
但是没有找到这方面的知识点  请问有相关文档分享下吗 感谢

**Comment by wi1dcard** [comment]
这是由于 PHP 的面向对象特性决定的。

根据 [官方文档](http://php.net/manual/en/language.oop5.static.php) 的描述：

> Declaring class properties or methods as static makes them accessible without needing an instantiation of the class. A property declared as static cannot be accessed with an instantiated class object (though a static method can).

使用 `static` 关键字并不是真正地将方法定义为「静态方法」，而是「makes them accessible without needing an instantiation of the class（使它们无需类实例也可被访问）」。除此之外，没有其它差异。你可测试以下代码：

```php
class FooBar
{
  public static function foo() {}

  public function foo() {}
}

// Fatal error: Cannot redeclare FooBar::foo()
```
