### ISSUE TITLE
为什么会有两个user_id：alipay_user_id，user_id？官方文档只有一个user_id。

### ISSUE THREAD

**Issue by weasiser** [wi1dcard/alipay-sdk-php#13]
![image](https://user-images.githubusercontent.com/28592681/58384585-e075dd00-8015-11e9-911e-f29f04cafb15.png)

**Comment by wi1dcard** [comment]
不太清楚你所描述的上下文是什么？是哪里多了 `alipay_user_id`？

**Comment by weasiser** [comment]
![image](https://user-images.githubusercontent.com/28592681/58389655-f78ced00-805e-11e9-805c-b917d12e94b0.png)
官方文档只有一个 user_id，没有 alipay_user_id，这个 alipay_user_id 难道是开发者自己的 id ?

**Comment by wi1dcard** [comment]
@weasiser 本 SDK 中，最终获取到的响应数据，是支付宝发回的原始数据直接反序列化后的结果，并没有增加任何参数。如果你对返回结果有疑问，可以使用 `AlipayResponse` 类的 `getRaw()` 方法：

<https://github.com/wi1dcard/alipay-sdk-php/blob/ecc0516792a2c8a859a469d770f28dc3dc9d7a3b/aop/AlipayResponse.php#L98-L106>

获取原始的响应字符串。

**Comment by weasiser** [comment]
另外，我按照你教程 alipay.system.oauth.token.md ，用你的sdk能得到响应数据，然后放在自己的项目上就出问题（我的是laravel 5.8），生成公钥私钥都是用那个 /bin/genrsa 工具生成的：
![image](https://user-images.githubusercontent.com/28592681/58390380-aaf7e080-8063-11e9-837e-9426ff2893d3.png)

这是我的一些代码：
![image](https://user-images.githubusercontent.com/28592681/58390491-1346c200-8064-11e9-8cab-ad38f6a55bef.png)

![image](https://user-images.githubusercontent.com/28592681/58390454-ee524f00-8063-11e9-86b8-310657d94bf7.png)

![image](https://user-images.githubusercontent.com/28592681/58390525-3e311600-8064-11e9-896e-219399db41ac.png)

![image](https://user-images.githubusercontent.com/28592681/58390554-586af400-8064-11e9-9728-7e9232649709.png)

![image](https://user-images.githubusercontent.com/28592681/58390581-7c2e3a00-8064-11e9-98ee-f83a6e9ffe05.png)

**Comment by wi1dcard** [comment]
试试看将 `env('ALIPAY_APP_PRIVATE_KEY')` 和 `env('ALIPAY_PUBLIC_KEY')` 修改为：

```php
base_path(env('ALIPAY_APP_PRIVATE_KEY'));

base_path(env('ALIPAY_PUBLIC_KEY'));
```

或是尝试使用绝对路径，先确保能够读到 Key 值。

另外，请使用 Markdown 的 Code Block 语法，截图不利于观看，也不利于大家审阅和修改你的代码。

**Comment by ztqgit** [comment]
部分问题可以到支付宝开放平台查询，alipay_user_id是废弃的
https://open.alipay.com/search/searchDetail.htm?tabType=api&keyword=alipay_user_id

**Comment by weasiser** [comment]
@wi1dcard 绝对路径的确可以读到 key ，非常感谢。
@ztqgit 谢谢提醒
