### ISSUE TITLE
新接手的项目引入了作者的包,但是已经不维护了吗

### ISSUE THREAD

**Issue by cpj555** [wi1dcard/alipay-sdk-php#21]
"wi1dcard/sentry": "dev-master",
        "wi1dcard/yii2-opening-storage": "dev-master",
        "wi1dcard/yii2-opening-express": "dev-master",
        "wi1dcard/yii2-opening-sms": "dev-master",
        "wi1dcard/yii2-opening-event": "dev-master"

**Comment by wi1dcard** [comment]
不好意思，请问是什么项目？

**Comment by cpj555** [comment]
从外包公司买来的商城系统,现在这几包没了 composer update  都没法用了

**Comment by wi1dcard** [comment]
不好意思，很遗憾地告诉你，这份商城代码的来源应该是非正当途径。这几个包是未公开的私有源；另外包名也经过篡改，原包名包含正版商城系统的名称。
