### ISSUE TITLE
支付宝密钥的问题

### ISSUE THREAD

**Issue by T-raun** [wi1dcard/alipay-sdk-php#22]
报 error:0906D06C:PEM routines:PEM_read_bio:no start line 错误

**Comment by wi1dcard** [comment]
猜测可能是证书缺少 `-----BEGIN CERTIFICATE-----` 或类似的 Start Line 导致，请检查。

**Comment by Abbotton** [comment]
感谢提交issue:beers:，抱歉姗姗来迟的回复，v2.0已经发布，欢迎使用并提出宝贵意见。
因时间久远本issue暂时关闭，如有需要请另开一个新的issue，谢谢。
